#pragma kernel KernelNone
#pragma kernel KernelACES
#pragma kernel KernelNeutral
#pragma kernel KernelReinhard

#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl"

RW_TEXTURE3D(float4, _ColorGradingLUT);

float4 _ColorAdjustments;
float4 _ColorFilter;
float4 _WhiteBalance;
float4 _SplitToningShadows, _SplitToningHighlights;
float4 _ChannelMixerRed, _ChannelMixerGreen, _ChannelMixerBlue;
float4 _SMHShadows, _SMHMidtones, _SMHHighlights, _SMHRange;
float4 _ColorGradingLUTParameters;

float Luminance(float3 color, bool useACES)
{
    return useACES ? AcesLuminance(color) : Luminance(color);
}

float3 ColorGradePostExposure(float3 color)
{
    return color * _ColorAdjustments.x;
}

float3 ColorGradeWhiteBalance(float3 color)
{
    color = LinearToLMS(color);
    color *= _WhiteBalance.rgb;
    return LMSToLinear(color);
}

float3 ColorGradingContrast(float3 color, bool useACES)
{
    color = useACES
        ? ACES_to_ACEScc(unity_to_ACES(color))
        : LinearToLogC(color);
    color = (color - ACEScc_MIDGRAY) * _ColorAdjustments.y + ACEScc_MIDGRAY;
    return useACES
        ? ACES_to_ACEScg(ACEScc_to_ACES(color))
        : LogCToLinear(color);
}

float3 ColorGradeColorFilter(float3 color)
{
    return color * _ColorFilter.rgb;
}

float3 ColorGradeSplitToning(float3 color, bool useACES)
{
    color = PositivePow(color, 1.0 / 2.2);
    float t = saturate(
        Luminance(saturate(color), useACES) + _SplitToningShadows.w);
    float3 shadows = lerp(0.5, _SplitToningShadows.rgb, 1.0 - t);
    float3 highlights = lerp(0.5, _SplitToningHighlights.rgb, t);
    color = SoftLight(color, shadows);
    color = SoftLight(color, highlights);
    return PositivePow(color, 2.2);
}

float3 ColorGradingChannelMixer(float3 color)
{
    return mul(
        float3x3(
            _ChannelMixerRed.rgb,
            _ChannelMixerGreen.rgb,
            _ChannelMixerBlue.rgb),
        color);
}

float3 ColorGradingShadowsMidtonesHighlights(float3 color, bool useACES)
{
    float luminance = Luminance(color, useACES);
    float shadowsWeight = 1.0 - smoothstep(_SMHRange.x, _SMHRange.y, luminance);
    float highlightsWeight = smoothstep(_SMHRange.z, _SMHRange.w, luminance);
    float midtonesWeight = 1.0 - shadowsWeight - highlightsWeight;
    return
        color * _SMHShadows.rgb * shadowsWeight +
        color * _SMHMidtones.rgb * midtonesWeight +
        color * _SMHHighlights.rgb * highlightsWeight;
}

float3 ColorGradingHueShift(float3 color)
{
    color = RgbToHsv(color);
    float hue = color.x + _ColorAdjustments.z;
    color.x = RotateHue(hue, 0.0, 1.0);
    return HsvToRgb(color);
}

float3 ColorGradingSaturation(float3 color, bool useACES)
{
    float luminance = Luminance(color, useACES);
    return (color - luminance) * _ColorAdjustments.w + luminance;
}

float3 ColorGrade(float3 color, bool useACES = false)
{
    color = ColorGradePostExposure(color);
    color = ColorGradeWhiteBalance(color);
    color = ColorGradingContrast(color, useACES);
    color = ColorGradeColorFilter(color);
    color = max(color, 0.0);
    color = ColorGradeSplitToning(color, useACES);
    color = ColorGradingChannelMixer(color);
    color = max(color, 0.0);
    color = ColorGradingShadowsMidtonesHighlights(color, useACES);
    color = ColorGradingHueShift(color);
    color = ColorGradingSaturation(color, useACES);
    return max(useACES ? ACEScg_to_ACES(color) : color, 0.0);
}

float3 GetColorGradedLUT(uint3 id, bool useACES = false)
{
    float3 color = id.xyz * _ColorGradingLUTParameters.w;
    return ColorGrade(
        _ColorGradingLUTParameters.x ? LogCToLinear(color) : color, useACES);
}

[numthreads(4, 4, 4)]
void KernelNone(uint3 id : SV_DispatchThreadID)
{
    float3 color = GetColorGradedLUT(id);
    _ColorGradingLUT[id.xyz] = float4(color, 0.0);
}

[numthreads(4, 4, 4)]
void KernelACES(uint3 id : SV_DispatchThreadID)
{
    float3 color = GetColorGradedLUT(id, true);
    color = AcesTonemap(color);
    _ColorGradingLUT[id.xyz] = float4(color, 0.0);
}

[numthreads(4, 4, 4)]
void KernelNeutral(uint3 id : SV_DispatchThreadID)
{
    float3 color = GetColorGradedLUT(id);
    color = NeutralTonemap(color);
    _ColorGradingLUT[id.xyz] = float4(color, 0.0);
}

[numthreads(4, 4, 4)]
void KernelReinhard(uint3 id : SV_DispatchThreadID)
{
    float3 color = GetColorGradedLUT(id);
    color /= color + 1.0;
    _ColorGradingLUT[id.xyz] = float4(color, 0.0);
}
